### PR TITLE
Fix missing user in Auth. get rid of last error from material ui?

### PR DESCRIPTION
**Pull request by joerou**

### CODE REVIEW

**Review by wswoodruff — COMMENTED** [review]
Looks good but got a couple questions:
1) How trusting can we be of the client side to be truthful about `this.userId`? Does Meteor magic ensure this is correct and secure? Since we've eliminated server-side-only checking from the equation I'm worried about that kinda stuff
2) Trying to think of a way to kick out unauthorized users in a more automated way. Perhaps checking args for an `_id` and checking the `returns` prop to know what to check on. This would also probably cause need for an extra prop besides just `auth: true`

**Comment by joerou** [comment]
I had to go look up some stuff to confirm :D

1. It's not relevant if the client side can be trusted in this case because the function is run on the client only to supply the optimistic ui with an approximation of what the outcome on the server will be. The method is then run separately on the server this.userId is not passed to the server method from the client but rather built in to Meteor's implementation of the server method. I couldn't find the article, but meteor builds this functionality into the DDP connection and it can't be tampered with. 

[Meteor Forum on userId](https://forums.meteor.com/t/how-do-meteor-userid-this-userid-and-meteor-user-work-internally/28043/5)

2. If you want to define auth: true as (loggedIn == true && this.userId == object.userId) then we can do that too, but I'm not sure that's smart in the long run? Probably you ability to edit something will be permissions/role based rather than ownership based? It might be worth taking a look at this implementation [LoggedIn Mixin](https://github.com/nabiltntn/loggedin-mixin/) We could easily utilize this same architecture for a lot of the things you are looking to accomplish. Creating "mixins" rather than some args and then what will soon be a really long function based on all of those args?

**Review by wswoodruff — APPROVED** [review]
@joerou Some context here: You are far more experienced with Meteor than I. Thanks for the thoughts and response.

`1` — Your explanation is sufficient for me.
`2` — The suggestion for building up our auth structure with mixins seems great!

**Comment by joerou** [comment]
Nice!

**Pull request merged**
